package com.hib;
// Generated Jun 28, 2017 1:40:49 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Answers generated by hbm2java
 */
@Entity(name = "Answer")
@Table(name = "Answers")
public class Answers implements java.io.Serializable {

    @Id
    private int slno;
    @ManyToOne
    @JoinColumn(name ="questid" )
    private Questionbank questionbank;
    @Column(name = "answer")
    private String answer;

    public Answers() {
    }

    public Answers(int slno) {
        this.slno = slno;
    }

    public Answers(int slno, Questionbank questionbank, String answer) {
        this.slno = slno;
        this.questionbank = questionbank;
        this.answer = answer;
    }

    public int getSlno() {
        return this.slno;
    }

    public void setSlno(int slno) {
        this.slno = slno;
    }

    public Questionbank getQuestionbank() {
        return this.questionbank;
    }

    public void setQuestionbank(Questionbank questionbank) {
        this.questionbank = questionbank;
    }

    public String getAnswer() {
        return this.answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

}
